name: linkedin_carousel
services:
    web:
        build:
            context: /home/senpai/Dev/linkedin_carousel
            dockerfile: Dockerfile
        cpu_shares: 90
        command: []
        container_name: linkedin-carousel
        deploy:
            resources:
                limits:
                    memory: "3634364416"
        environment:
            DEEPSEEK_API_KEY: DEEPSEEK_API_KEY_PLACEHOLDER
            GOOGLE_GEMINI_API_KEY: GOOGLE_GEMINI_API_KEY_PLACEHOLDER
            NODE_ENV: production
        env_file:
            - /home/senpai/Dev/linkedin_carousel/.env
        hostname: linkedin-carousel
        image: aman-senpai/linkedin-carousel:latest
        labels:
            icon: https://cdn-icons-png.flaticon.com/512/174/174857.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: 3000
              published: "3000"
              protocol: tcp
        restart: unless-stopped
networks:
    default:
        name: linkedin_carousel_default
x-casaos:
    architectures:
        - amd64
        - arm64
        - arm
    author: Senpai
    category: Productivity
    description:
        en_us: LinkedIn Carousel Generator
    developer: Senpai
    hostname: ""
    icon: https://cdn-icons-png.flaticon.com/512/174/174857.png
    index: /
    is_uncontrolled: false
    main: web
    port_map: "3000"
    scheme: http
    tagline:
        en_us: Generate LinkedIn Carousels efficiently.
    thumbnail: https://cdn-icons-png.flaticon.com/512/174/174857.png
    title:
        custom: ""
        en_us: LinkedIn Carousel
