// 125 Unique Visual Templates for LinkedIn Carousel
// Each template has its own distinct visual style, decorations, and layout modifications

export const TEMPLATES = [
    // 1. Modern Corporate
    {
        id: "modern",
        name: "Modern Corporate",
        category: "Business",
        description: "Clean, professional design with floating gradients",
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#60a5fa",
        dark: "#0f172a",
        light: "#f8fafc",
        gradient: { from: "#3b82f6", to: "#1e40af", direction: "to-br" },
        decorationType: "floating-circles",
        headingStyle: "font-extrabold tracking-tight",
        cardStyle: "rounded-3xl shadow-xl",
        accentShape: "circle",
    },
    // 2. Marvel Comics
    {
        id: "marvel",
        name: "Marvel",
        category: "Comics",
        description: "Bold comic-book style with halftone effects",
        primary: "#ED1D24",
        secondary: "#FFD700",
        accent: "#B22222",
        dark: "#1a1a2e",
        light: "#fff5f5",
        gradient: { from: "#ED1D24", to: "#FFD700", direction: "to-br" },
        decorationType: "comic-halftone",
        headingStyle: "font-black uppercase tracking-wider",
        cardStyle: "border-8 border-black shadow-[8px_8px_0_0_#000]",
        accentShape: "burst",
    },
    // 3. DC Universe
    {
        id: "dc",
        name: "DC Universe",
        category: "Comics",
        description: "Heroic design with dramatic lighting",
        primary: "#0476F5",
        secondary: "#C8102E",
        accent: "#FFD700",
        dark: "#0a1628",
        light: "#f0f7ff",
        gradient: { from: "#0476F5", to: "#C8102E", direction: "to-r" },
        decorationType: "hero-rays",
        headingStyle: "font-black uppercase tracking-wide",
        cardStyle: "border-4 border-yellow-400 rounded-lg",
        accentShape: "shield",
    },
    // 4. Gotham Dark
    {
        id: "gotham",
        name: "Gotham Dark",
        category: "Comics",
        description: "Dark noir style with dramatic shadows",
        primary: "#FFC107",
        secondary: "#212121",
        accent: "#424242",
        dark: "#0d0d0d",
        light: "#2d2d2d",
        gradient: { from: "#212121", to: "#FFC107", direction: "to-tr" },
        decorationType: "noir-shadows",
        headingStyle: "font-bold italic tracking-tight",
        cardStyle: "rounded-none border-l-8",
        accentShape: "bat",
    },
    // 5. Spider-Verse
    {
        id: "spiderverse",
        name: "Spider-Verse",
        category: "Comics",
        description: "Glitchy, multi-dimensional comic style",
        primary: "#E23636",
        secondary: "#2196F3",
        accent: "#FF4081",
        dark: "#1a0a2e",
        light: "#fff0f3",
        gradient: { from: "#E23636", to: "#2196F3", direction: "to-bl" },
        decorationType: "glitch-layers",
        headingStyle: "font-black tracking-tighter",
        cardStyle: "rounded-2xl border-4 border-dashed",
        accentShape: "web",
    },
    // 6. Wakanda
    {
        id: "wakanda",
        name: "Wakanda",
        category: "Comics",
        description: "Afrofuturistic tribal tech design",
        primary: "#9C27B0",
        secondary: "#212121",
        accent: "#7B1FA2",
        dark: "#0f0a1a",
        light: "#f3e5f5",
        gradient: { from: "#9C27B0", to: "#212121", direction: "to-b" },
        decorationType: "tribal-tech",
        headingStyle: "font-bold tracking-widest uppercase",
        cardStyle: "rounded-xl border-2",
        accentShape: "diamond",
    },
    // 7. Asgard
    {
        id: "asgard",
        name: "Asgard",
        category: "Fantasy",
        description: "Norse mythology with golden accents",
        primary: "#00BCD4",
        secondary: "#FFD700",
        accent: "#E91E63",
        dark: "#0a1a2a",
        light: "#e0f7fa",
        gradient: { from: "#00BCD4", to: "#FFD700", direction: "to-r" },
        decorationType: "norse-runes",
        headingStyle: "font-bold tracking-wide",
        cardStyle: "rounded-lg border-4 border-double",
        accentShape: "thunder",
    },
    // 8. Cyberpunk
    {
        id: "cyberpunk",
        name: "Cyberpunk 2077",
        category: "Futuristic",
        description: "Neon-lit dystopian future",
        primary: "#00FFFF",
        secondary: "#FF00FF",
        accent: "#FFFF00",
        dark: "#0a0a0f",
        light: "#1a1a2e",
        gradient: { from: "#FF00FF", to: "#00FFFF", direction: "to-r" },
        decorationType: "neon-grid",
        headingStyle: "font-black uppercase tracking-[0.2em]",
        cardStyle: "border-2 border-cyan-400 rounded-none",
        accentShape: "hexagon",
    },
    // 9. Synthwave
    {
        id: "synthwave",
        name: "Synthwave",
        category: "Retro",
        description: "80s retro-futuristic vibes",
        primary: "#FF6EC7",
        secondary: "#7B68EE",
        accent: "#00CED1",
        dark: "#1a0a2e",
        light: "#2d1b4e",
        gradient: { from: "#FF6EC7", to: "#7B68EE", direction: "to-br" },
        decorationType: "retro-sun",
        headingStyle: "font-bold italic",
        cardStyle: "rounded-xl border-b-4",
        accentShape: "sun",
    },
    // 10. Ocean Deep
    {
        id: "ocean",
        name: "Ocean Deep",
        category: "Nature",
        description: "Calm underwater aesthetics",
        primary: "#006994",
        secondary: "#00CED1",
        accent: "#20B2AA",
        dark: "#001f3f",
        light: "#e6f7ff",
        gradient: { from: "#006994", to: "#00CED1", direction: "to-b" },
        decorationType: "wave-pattern",
        headingStyle: "font-light tracking-widest",
        cardStyle: "rounded-3xl",
        accentShape: "wave",
    },
    // 11. Sunset Beach
    {
        id: "sunset",
        name: "Sunset Beach",
        category: "Nature",
        description: "Warm golden hour colors",
        primary: "#FF6B35",
        secondary: "#F7931E",
        accent: "#FFD93D",
        dark: "#2d1810",
        light: "#fff8f0",
        gradient: { from: "#FF6B35", to: "#FFD93D", direction: "to-tr" },
        decorationType: "sun-rays",
        headingStyle: "font-semibold tracking-wide",
        cardStyle: "rounded-2xl shadow-lg",
        accentShape: "circle",
    },
    // 12. Midnight Galaxy
    {
        id: "galaxy",
        name: "Midnight Galaxy",
        category: "Space",
        description: "Cosmic space exploration",
        primary: "#667eea",
        secondary: "#764ba2",
        accent: "#f093fb",
        dark: "#0c0c1e",
        light: "#1e1e3f",
        gradient: { from: "#667eea", to: "#764ba2", direction: "to-br" },
        decorationType: "stars",
        headingStyle: "font-light tracking-[0.15em]",
        cardStyle: "rounded-full overflow-hidden",
        accentShape: "star",
    },
    // 13. Neon Tokyo
    {
        id: "tokyo",
        name: "Neon Tokyo",
        category: "Urban",
        description: "Japanese neon city lights",
        primary: "#FF2D95",
        secondary: "#00F5FF",
        accent: "#9D00FF",
        dark: "#0f0f23",
        light: "#1f1f3f",
        gradient: { from: "#FF2D95", to: "#00F5FF", direction: "to-r" },
        decorationType: "kanji-overlay",
        headingStyle: "font-black tracking-tight",
        cardStyle: "rounded-lg border-l-4",
        accentShape: "rectangle",
    },
    // 14. Forest Mystic
    {
        id: "forest",
        name: "Forest Mystic",
        category: "Nature",
        description: "Enchanted forest vibes",
        primary: "#2ECC71",
        secondary: "#1ABC9C",
        accent: "#27AE60",
        dark: "#0a1f0a",
        light: "#e8f8f0",
        gradient: { from: "#2ECC71", to: "#1ABC9C", direction: "to-bl" },
        decorationType: "leaf-pattern",
        headingStyle: "font-medium tracking-wide",
        cardStyle: "rounded-3xl border-2 border-green-200",
        accentShape: "leaf",
    },
    // 15. Golden Hour
    {
        id: "golden",
        name: "Golden Hour",
        category: "Luxury",
        description: "Premium gold aesthetics",
        primary: "#D4AF37",
        secondary: "#B8860B",
        accent: "#FFD700",
        dark: "#1a1507",
        light: "#fffbe6",
        gradient: { from: "#D4AF37", to: "#FFD700", direction: "to-tr" },
        decorationType: "gold-particles",
        headingStyle: "font-light tracking-[0.2em] uppercase",
        cardStyle: "rounded-xl border-2 border-yellow-400",
        accentShape: "diamond",
    },
    // 16. Arctic Frost
    {
        id: "arctic",
        name: "Arctic Frost",
        category: "Nature",
        description: "Cool icy minimalism",
        primary: "#74b9ff",
        secondary: "#0984e3",
        accent: "#a29bfe",
        dark: "#0a1929",
        light: "#f5f9ff",
        gradient: { from: "#74b9ff", to: "#a29bfe", direction: "to-r" },
        decorationType: "frost-crystals",
        headingStyle: "font-thin tracking-widest",
        cardStyle: "rounded-2xl backdrop-blur-sm",
        accentShape: "snowflake",
    },
    // 17. Volcanic Fire
    {
        id: "volcanic",
        name: "Volcanic Fire",
        category: "Intense",
        description: "Explosive fiery energy",
        primary: "#FF4500",
        secondary: "#DC143C",
        accent: "#FF6347",
        dark: "#1a0500",
        light: "#fff0e6",
        gradient: { from: "#FF4500", to: "#DC143C", direction: "to-b" },
        decorationType: "fire-embers",
        headingStyle: "font-black uppercase",
        cardStyle: "rounded-lg border-4 border-orange-500",
        accentShape: "flame",
    },
    // 18. Cherry Blossom
    {
        id: "sakura",
        name: "Cherry Blossom",
        category: "Elegant",
        description: "Delicate Japanese spring",
        primary: "#FFB7C5",
        secondary: "#FF69B4",
        accent: "#FFC0CB",
        dark: "#2d1f24",
        light: "#fff5f7",
        gradient: { from: "#FFB7C5", to: "#FF69B4", direction: "to-br" },
        decorationType: "sakura-petals",
        headingStyle: "font-light tracking-wide",
        cardStyle: "rounded-3xl shadow-pink-200",
        accentShape: "flower",
    },
    // 19. Electric Storm
    {
        id: "storm",
        name: "Electric Storm",
        category: "Intense",
        description: "Powerful electrical energy",
        primary: "#9B59B6",
        secondary: "#3498DB",
        accent: "#F1C40F",
        dark: "#1a1025",
        light: "#f5f0ff",
        gradient: { from: "#9B59B6", to: "#3498DB", direction: "to-bl" },
        decorationType: "lightning-bolts",
        headingStyle: "font-bold tracking-tight",
        cardStyle: "rounded-xl border-2 border-purple-400",
        accentShape: "bolt",
    },
    // 20. Vintage Sepia
    {
        id: "vintage",
        name: "Vintage Sepia",
        category: "Classic",
        description: "Old-world classic charm",
        primary: "#8B4513",
        secondary: "#A0522D",
        accent: "#D2691E",
        dark: "#1f1408",
        light: "#faf0e6",
        gradient: { from: "#8B4513", to: "#D2691E", direction: "to-r" },
        decorationType: "vintage-texture",
        headingStyle: "font-serif tracking-normal",
        cardStyle: "rounded-none border-8 border-double",
        accentShape: "frame",
    },
    // 21. Holographic
    {
        id: "holographic",
        name: "Holographic",
        category: "Futuristic",
        description: "Iridescent rainbow effects",
        primary: "#E040FB",
        secondary: "#00E5FF",
        accent: "#76FF03",
        dark: "#0a0a1f",
        light: "#f0f0ff",
        gradient: { from: "#E040FB", to: "#00E5FF", direction: "to-tr" },
        decorationType: "hologram-lines",
        headingStyle: "font-bold tracking-wide",
        cardStyle: "rounded-2xl border-2",
        accentShape: "prism",
    },
    // 22. Minimal Zen
    {
        id: "zen",
        name: "Minimal Zen",
        category: "Minimal",
        description: "Clean, peaceful simplicity",
        primary: "#6b7280",
        secondary: "#9ca3af",
        accent: "#4b5563",
        dark: "#111827",
        light: "#f9fafb",
        gradient: { from: "#6b7280", to: "#9ca3af", direction: "to-b" },
        decorationType: "single-line",
        headingStyle: "font-extralight tracking-[0.3em]",
        cardStyle: "rounded-none border-b",
        accentShape: "line",
    },
    // 23. Brutalist
    {
        id: "brutalist",
        name: "Brutalist",
        category: "Bold",
        description: "Raw, unpolished power",
        primary: "#000000",
        secondary: "#ffffff",
        accent: "#ff0000",
        dark: "#000000",
        light: "#ffffff",
        gradient: { from: "#000000", to: "#333333", direction: "to-b" },
        decorationType: "harsh-lines",
        headingStyle: "font-black uppercase tracking-tighter",
        cardStyle: "border-8 border-black",
        accentShape: "square",
    },
    // 24. Pastel Dream
    {
        id: "pastel",
        name: "Pastel Dream",
        category: "Soft",
        description: "Soft, dreamy aesthetics",
        primary: "#a78bfa",
        secondary: "#f9a8d4",
        accent: "#6ee7b7",
        dark: "#312e81",
        light: "#faf5ff",
        gradient: { from: "#a78bfa", to: "#f9a8d4", direction: "to-br" },
        decorationType: "soft-blobs",
        headingStyle: "font-medium tracking-wide",
        cardStyle: "rounded-3xl shadow-lg",
        accentShape: "blob",
    },
    // 25. Matrix
    {
        id: "matrix",
        name: "Matrix",
        category: "Tech",
        description: "Digital rain code",
        primary: "#00ff41",
        secondary: "#008f11",
        accent: "#00ff41",
        dark: "#000000",
        light: "#001100",
        gradient: { from: "#00ff41", to: "#008f11", direction: "to-b" },
        decorationType: "matrix-rain",
        headingStyle: "font-mono font-bold",
        cardStyle: "border-2 border-green-500 rounded-none",
        accentShape: "code",
    },
    // 26. Vaporwave
    {
        id: "vaporwave",
        name: "Vaporwave",
        category: "Retro",
        description: "90s aesthetic nostalgia",
        primary: "#ff71ce",
        secondary: "#01cdfe",
        accent: "#05ffa1",
        dark: "#1a0033",
        light: "#2d004d",
        gradient: { from: "#ff71ce", to: "#01cdfe", direction: "to-bl" },
        decorationType: "vaporwave-grid",
        headingStyle: "font-bold italic tracking-wide",
        cardStyle: "rounded-xl border-4",
        accentShape: "palm",
    },
    // 27-125: Expanding the library with 100 more variations
    {
        id: "indigo-flow",
        name: "Indigo Flow",
        category: "Business",
        description: "Smooth indigo gradients for corporate storytelling",
        primary: "#4f46e5",
        secondary: "#312e81",
        accent: "#818cf8",
        dark: "#1e1b4b",
        light: "#f5f3ff",
        gradient: { from: "#4f46e5", to: "#312e81", direction: "to-br" },
        decorationType: "floating-circles",
        headingStyle: "font-bold tracking-tight",
        cardStyle: "rounded-3xl shadow-xl",
        accentShape: "circle",
    },
    {
        id: "crimson-edge",
        name: "Crimson Edge",
        category: "Bold",
        description: "Aggressive crimson design for high impact",
        primary: "#dc2626",
        secondary: "#7f1d1d",
        accent: "#f87171",
        dark: "#450a0a",
        light: "#fef2f2",
        gradient: { from: "#dc2626", to: "#7f1d1d", direction: "to-r" },
        decorationType: "harsh-lines",
        headingStyle: "font-black uppercase",
        cardStyle: "border-l-8 border-red-600",
        accentShape: "rectangle",
    },
    {
        id: "emerald-trust",
        name: "Emerald Trust",
        category: "Business",
        description: "Finance and trust focused emerald palette",
        primary: "#059669",
        secondary: "#064e3b",
        accent: "#34d399",
        dark: "#022c22",
        light: "#f0fdf4",
        gradient: { from: "#059669", to: "#064e3b", direction: "to-bl" },
        decorationType: "single-line",
        headingStyle: "font-semibold",
        cardStyle: "rounded-2xl shadow-md border border-emerald-100",
        accentShape: "line",
    },
    {
        id: "amber-glow",
        name: "Amber Glow",
        category: "Warm",
        description: "Inviting amber and gold tones",
        primary: "#d97706",
        secondary: "#78350f",
        accent: "#fbbf24",
        dark: "#451a03",
        light: "#fffbeb",
        gradient: { from: "#d97706", to: "#fbbf24", direction: "to-tr" },
        decorationType: "sun-rays",
        headingStyle: "font-bold",
        cardStyle: "rounded-xl shadow-lg",
        accentShape: "circle",
    },
    {
        id: "slate-pro",
        name: "Slate Professional",
        category: "Minimal",
        description: "Understated slate for technical content",
        primary: "#475569",
        secondary: "#1e293b",
        accent: "#94a3b8",
        dark: "#0f172a",
        light: "#f8fafc",
        gradient: { from: "#475569", to: "#1e293b", direction: "to-b" },
        decorationType: "floating-circles",
        headingStyle: "font-medium tracking-wide",
        cardStyle: "rounded-lg border border-slate-200",
        accentShape: "circle",
    },
    {
        id: "violet-surge",
        name: "Violet Surge",
        category: "Futuristic",
        description: "Energetic violet for startups and tech",
        primary: "#7c3aed",
        secondary: "#4c1d95",
        accent: "#a78bfa",
        dark: "#2e1065",
        light: "#f5f3ff",
        gradient: { from: "#7c3aed", to: "#4c1d95", direction: "to-br" },
        decorationType: "glitch-layers",
        headingStyle: "font-extrabold italic",
        cardStyle: "rounded-3xl border-2 border-violet-200",
        accentShape: "bolt",
    },
    {
        id: "rose-whisper",
        name: "Rose Whisper",
        category: "Soft",
        description: "Gentle rose for lifestyle and wellness",
        primary: "#db2777",
        secondary: "#831843",
        accent: "#f472b6",
        dark: "#500724",
        light: "#fff1f2",
        gradient: { from: "#db2777", to: "#f472b6", direction: "to-r" },
        decorationType: "soft-blobs",
        headingStyle: "font-light tracking-widest",
        cardStyle: "rounded-full px-8",
        accentShape: "blob",
    },
    {
        id: "teal-horizon",
        name: "Teal Horizon",
        category: "Nature",
        description: "Refreshing teal for environmental topics",
        primary: "#0d9488",
        secondary: "#134e4a",
        accent: "#2dd4bf",
        dark: "#042f2e",
        light: "#f0fdfa",
        gradient: { from: "#0d9488", to: "#134e4a", direction: "to-t" },
        decorationType: "wave-pattern",
        headingStyle: "font-semibold tracking-tight",
        cardStyle: "rounded-2xl shadow-teal-100",
        accentShape: "wave",
    },
    {
        id: "orange-blast",
        name: "Orange Blast",
        category: "Bold",
        description: "High-energy orange for marketing",
        primary: "#ea580c",
        secondary: "#7c2d12",
        accent: "#fb923c",
        dark: "#431407",
        light: "#fff7ed",
        gradient: { from: "#ea580c", to: "#fb923c", direction: "to-br" },
        decorationType: "hero-rays",
        headingStyle: "font-black italic",
        cardStyle: "rounded-none border-t-8 border-orange-600",
        accentShape: "burst",
    },
    {
        id: "lime-logic",
        name: "Lime Logic",
        category: "Tech",
        description: "Vibrant lime for coding and development",
        primary: "#65a30d",
        secondary: "#365314",
        accent: "#bef264",
        dark: "#1a2e05",
        light: "#f7fee7",
        gradient: { from: "#65a30d", to: "#365314", direction: "to-bl" },
        decorationType: "matrix-rain",
        headingStyle: "font-mono",
        cardStyle: "border-2 border-lime-500 rounded-md",
        accentShape: "code",
    },
    {
        id: "sky-limit",
        name: "Sky Limit",
        category: "Inspiration",
        description: "Airy blue for motivational quotes",
        primary: "#0284c7",
        secondary: "#0c4a6e",
        accent: "#38bdf8",
        dark: "#082f49",
        light: "#f0f9ff",
        gradient: { from: "#0284c7", to: "#38bdf8", direction: "to-tr" },
        decorationType: "stars",
        headingStyle: "font-thin uppercase tracking-[0.4em]",
        cardStyle: "rounded-3xl backdrop-blur-md",
        accentShape: "star",
    },
    {
        id: "fuchsia-flash",
        name: "Fuchsia Flash",
        category: "Creative",
        description: "Trendy fuchsia for design portfolios",
        primary: "#c026d3",
        secondary: "#701a75",
        accent: "#e879f9",
        dark: "#4a044e",
        light: "#fdf4ff",
        gradient: { from: "#c026d3", to: "#e879f9", direction: "to-r" },
        decorationType: "hologram-lines",
        headingStyle: "font-bold tracking-tighter",
        cardStyle: "rounded-xl border-4 border-fuchsia-300",
        accentShape: "prism",
    },
    {
        id: "coffee-break",
        name: "Coffee Break",
        category: "Warm",
        description: "Rich brown for casual networking",
        primary: "#92400e",
        secondary: "#451a03",
        accent: "#d97706",
        dark: "#2d1a10",
        light: "#fff9f2",
        gradient: { from: "#92400e", to: "#451a03", direction: "to-b" },
        decorationType: "vintage-texture",
        headingStyle: "font-serif italic",
        cardStyle: "rounded-2xl border-b-4 border-amber-900",
        accentShape: "frame",
    },
    {
        id: "mint-fresh",
        name: "Mint Fresh",
        category: "Minimal",
        description: "Clean mint for health and productivity",
        primary: "#059669",
        secondary: "#064e3b",
        accent: "#6ee7b7",
        dark: "#022c22",
        light: "#ecfdf5",
        gradient: { from: "#059669", to: "#6ee7b7", direction: "to-br" },
        decorationType: "leaf-pattern",
        headingStyle: "font-medium",
        cardStyle: "rounded-3xl shadow-sm",
        accentShape: "leaf",
    },
    {
        id: "gold-standard",
        name: "Gold Standard",
        category: "Luxury",
        description: "Ultimate luxury gold and black",
        primary: "#fbbf24",
        secondary: "#000000",
        accent: "#fcd34d",
        dark: "#000000",
        light: "#111111",
        gradient: { from: "#fbbf24", to: "#000000", direction: "to-br" },
        decorationType: "gold-particles",
        headingStyle: "font-black uppercase tracking-widest",
        cardStyle: "border-2 border-yellow-500 rounded-none",
        accentShape: "diamond",
    },
    {
        id: "ruby-rare",
        name: "Ruby Rare",
        category: "Luxury",
        description: "Deep ruby for exclusive insights",
        primary: "#be123c",
        secondary: "#4c0519",
        accent: "#fb7185",
        dark: "#2a020d",
        light: "#fff1f2",
        gradient: { from: "#be123c", to: "#4c0519", direction: "to-bl" },
        decorationType: "hero-rays",
        headingStyle: "font-bold",
        cardStyle: "rounded-lg border-2 border-ruby-200",
        accentShape: "shield",
    },
    {
        id: "cyan-cyber",
        name: "Cyan Cyber",
        category: "Tech",
        description: "Electric cyan for software engineering",
        primary: "#0891b2",
        secondary: "#164e63",
        accent: "#22d3ee",
        dark: "#083344",
        light: "#ecfeff",
        gradient: { from: "#0891b2", to: "#164e63", direction: "to-r" },
        decorationType: "neon-grid",
        headingStyle: "font-black tracking-wide",
        cardStyle: "border-l-4 border-cyan-500",
        accentShape: "hexagon",
    },
    {
        id: "charcoal-chic",
        name: "Charcoal Chic",
        category: "Fashion",
        description: "Sophisticated charcoal for style guides",
        primary: "#374151",
        secondary: "#111827",
        accent: "#6b7280",
        dark: "#030712",
        light: "#f9fafb",
        gradient: { from: "#374151", to: "#111827", direction: "to-b" },
        decorationType: "single-line",
        headingStyle: "font-thin uppercase",
        cardStyle: "rounded-none border-y border-gray-800",
        accentShape: "line",
    },
    {
        id: "lemon-twist",
        name: "Lemon Twist",
        category: "Warm",
        description: "Zesty yellow for upbeat content",
        primary: "#eab308",
        secondary: "#713f12",
        accent: "#fde047",
        dark: "#422006",
        light: "#fefce8",
        gradient: { from: "#eab308", to: "#fde047", direction: "to-tr" },
        decorationType: "sun-rays",
        headingStyle: "font-extrabold",
        cardStyle: "rounded-full px-12",
        accentShape: "circle",
    },
    {
        id: "periwinkle-pow",
        name: "Periwinkle Pow",
        category: "Comics",
        description: "Playful periwinkle comic style",
        primary: "#6366f1",
        secondary: "#312e81",
        accent: "#818cf8",
        dark: "#1e1b4b",
        light: "#eef2ff",
        gradient: { from: "#6366f1", to: "#312e81", direction: "to-br" },
        decorationType: "comic-halftone",
        headingStyle: "font-black tracking-tighter",
        cardStyle: "border-4 border-indigo-600 shadow-lg",
        accentShape: "burst",
    },
    {
        id: "forest-fable",
        name: "Forest Fable",
        category: "Fantasy",
        description: "Deep forest green for storytelling",
        primary: "#166534",
        secondary: "#064e3b",
        accent: "#4ade80",
        dark: "#052e16",
        light: "#f0fdf4",
        gradient: { from: "#166534", to: "#064e3b", direction: "to-bl" },
        decorationType: "leaf-pattern",
        headingStyle: "font-serif font-bold",
        cardStyle: "rounded-3xl border-l-8 border-green-800",
        accentShape: "leaf",
    },
    {
        id: "midnight-monarch",
        name: "Midnight Monarch",
        category: "Luxury",
        description: "Deep navy and gold for leadership",
        primary: "#1e3a8a",
        secondary: "#172554",
        accent: "#fbbf24",
        dark: "#0a1024",
        light: "#f0f4ff",
        gradient: { from: "#1e3a8a", to: "#172554", direction: "to-b" },
        decorationType: "gold-particles",
        headingStyle: "font-bold uppercase tracking-widest",
        cardStyle: "rounded-xl border-2 border-yellow-600 shadow-2xl",
        accentShape: "shield",
    },
    {
        id: "tangerine-dream",
        name: "Tangerine Dream",
        category: "Soft",
        description: "Soft tangerine for friendly advice",
        primary: "#f97316",
        secondary: "#9a3412",
        accent: "#fdba74",
        dark: "#431407",
        light: "#fff7ed",
        gradient: { from: "#f97316", to: "#fdba74", direction: "to-r" },
        decorationType: "soft-blobs",
        headingStyle: "font-medium tracking-wide",
        cardStyle: "rounded-2xl border border-orange-100",
        accentShape: "blob",
    },
    {
        id: "steel-strength",
        name: "Steel Strength",
        category: "Industrial",
        description: "Cold steel for construction and engineering",
        primary: "#64748b",
        secondary: "#334155",
        accent: "#cbd5e1",
        dark: "#0f172a",
        light: "#f1f5f9",
        gradient: { from: "#64748b", to: "#334155", direction: "to-tr" },
        decorationType: "harsh-lines",
        headingStyle: "font-black uppercase tracking-tight",
        cardStyle: "rounded-none border-4 border-slate-600 shadow-inner",
        accentShape: "rectangle",
    },
    {
        id: "amethyst-aura",
        name: "Amethyst Aura",
        category: "Fantasy",
        description: "Mystical purple for creative writing",
        primary: "#9333ea",
        secondary: "#581c87",
        accent: "#c084fc",
        dark: "#3b0764",
        light: "#faf5ff",
        gradient: { from: "#9333ea", to: "#581c87", direction: "to-br" },
        decorationType: "norse-runes",
        headingStyle: "font-light italic tracking-widest",
        cardStyle: "rounded-full border-2 border-purple-400",
        accentShape: "thunder",
    },
    {
        id: "glacier-glide",
        name: "Glacier Glide",
        category: "Nature",
        description: "Cool blue for data and analytics",
        primary: "#0ea5e9",
        secondary: "#0369a1",
        accent: "#7dd3fc",
        dark: "#082f49",
        light: "#f0f9ff",
        gradient: { from: "#0ea5e9", to: "#0369a1", direction: "to-bl" },
        decorationType: "frost-crystals",
        headingStyle: "font-bold tracking-tight",
        cardStyle: "rounded-3xl shadow-blue-100",
        accentShape: "snowflake",
    },
    {
        id: "lava-logic",
        name: "Lava Logic",
        category: "Intense",
        description: "Dark lava for controversial takes",
        primary: "#b91c1c",
        secondary: "#450a0a",
        accent: "#f87171",
        dark: "#111827",
        light: "#1f2937",
        gradient: { from: "#b91c1c", to: "#450a0a", direction: "to-b" },
        decorationType: "fire-embers",
        headingStyle: "font-black tracking-tighter",
        cardStyle: "border-l-8 border-red-900 bg-gray-900",
        accentShape: "flame",
    },
    {
        id: "sand-serenity",
        name: "Sand Serenity",
        category: "Minimal",
        description: "Neutral sand for professional simplicity",
        primary: "#a8a29e",
        secondary: "#57534e",
        accent: "#d6d3d1",
        dark: "#1c1917",
        light: "#fafaf9",
        gradient: { from: "#a8a29e", to: "#d6d3d1", direction: "to-tr" },
        decorationType: "single-line",
        headingStyle: "font-normal tracking-wide",
        cardStyle: "rounded-none border border-stone-200 shadow-sm",
        accentShape: "line",
    },
    {
        id: "ocean-oracle",
        name: "Ocean Oracle",
        category: "Inspiration",
        description: "Deep sea blue for wisdom and depth",
        primary: "#1e40af",
        secondary: "#1e3a8a",
        accent: "#60a5fa",
        dark: "#172554",
        light: "#eff6ff",
        gradient: { from: "#1e40af", to: "#1e3a8a", direction: "to-r" },
        decorationType: "wave-pattern",
        headingStyle: "font-light italic",
        cardStyle: "rounded-3xl border-t-4 border-blue-400",
        accentShape: "wave",
    },
    {
        id: "neon-nova",
        name: "Neon Nova",
        category: "Futuristic",
        description: "Hyper-vibrant neon for viral content",
        primary: "#a855f7",
        secondary: "#6b21a8",
        accent: "#d946ef",
        dark: "#2e1065",
        light: "#f5f3ff",
        gradient: { from: "#a855f7", to: "#d946ef", direction: "to-br" },
        decorationType: "neon-grid",
        headingStyle: "font-black uppercase tracking-widest",
        cardStyle:
            "border-4 border-purple-500 shadow-[0_0_20px_rgba(168,85,247,0.5)]",
        accentShape: "hexagon",
    },
    {
        id: "sage-story",
        name: "Sage Story",
        category: "Wellness",
        description: "Muted sage for coaching and mindfulness",
        primary: "#65a30d",
        secondary: "#3f6212",
        accent: "#bef264",
        dark: "#1a2e05",
        light: "#f7fee7",
        gradient: { from: "#65a30d", to: "#bef264", direction: "to-bl" },
        decorationType: "leaf-pattern",
        headingStyle: "font-medium tracking-tight",
        cardStyle: "rounded-2xl border-2 border-lime-100",
        accentShape: "leaf",
    },
    {
        id: "copper-craft",
        name: "Copper Craft",
        category: "Industrial",
        description: "Warm copper for manual skills and trades",
        primary: "#9a3412",
        secondary: "#431407",
        accent: "#ea580c",
        dark: "#2d0a05",
        light: "#fff7ed",
        gradient: { from: "#9a3412", to: "#ea580c", direction: "to-tr" },
        decorationType: "vintage-texture",
        headingStyle: "font-bold tracking-wide",
        cardStyle: "rounded-xl border-4 border-orange-900",
        accentShape: "frame",
    },
    {
        id: "bubblegum-biz",
        name: "Bubblegum Business",
        category: "Creative",
        description: "Fun pink for female entrepreneurship",
        primary: "#ec4899",
        secondary: "#9d174d",
        accent: "#f472b6",
        dark: "#500724",
        light: "#fdf2f8",
        gradient: { from: "#ec4899", to: "#f472b6", direction: "to-r" },
        decorationType: "soft-blobs",
        headingStyle: "font-extrabold",
        cardStyle: "rounded-3xl shadow-pink-100",
        accentShape: "blob",
    },
    {
        id: "slate-storm",
        name: "Slate Storm",
        category: "Tech",
        description: "Moody slate for deep technical dives",
        primary: "#1e293b",
        secondary: "#0f172a",
        accent: "#475569",
        dark: "#020617",
        light: "#f8fafc",
        gradient: { from: "#1e293b", to: "#0f172a", direction: "to-b" },
        decorationType: "lightning-bolts",
        headingStyle: "font-black tracking-tight",
        cardStyle: "rounded-none border-l-4 border-slate-400",
        accentShape: "bolt",
    },
    {
        id: "honey-help",
        name: "Honey Help",
        category: "Soft",
        description: "Warm honey for community and support",
        primary: "#d97706",
        secondary: "#78350f",
        accent: "#fbbf24",
        dark: "#451a03",
        light: "#fffbeb",
        gradient: { from: "#d97706", to: "#fbbf24", direction: "to-br" },
        decorationType: "sun-rays",
        headingStyle: "font-semibold",
        cardStyle: "rounded-3xl border border-amber-100 shadow-md",
        accentShape: "circle",
    },
    {
        id: "arctic-advise",
        name: "Arctic Advise",
        category: "Minimal",
        description: "Sharp icy blue for consulting",
        primary: "#0ea5e9",
        secondary: "#0c4a6e",
        accent: "#38bdf8",
        dark: "#082f49",
        light: "#f0f9ff",
        gradient: { from: "#0ea5e9", to: "#0c4a6e", direction: "to-t" },
        decorationType: "frost-crystals",
        headingStyle: "font-thin uppercase tracking-[0.2em]",
        cardStyle: "rounded-lg border-2 border-sky-100 shadow-sm",
        accentShape: "snowflake",
    },
    {
        id: "pine-peak",
        name: "Pine Peak",
        category: "Nature",
        description: "Deep pine green for outdoor and travel",
        primary: "#14532d",
        secondary: "#064e3b",
        accent: "#22c55e",
        dark: "#022c22",
        light: "#f0fdf4",
        gradient: { from: "#14532d", to: "#22c55e", direction: "to-tr" },
        decorationType: "leaf-pattern",
        headingStyle: "font-black",
        cardStyle: "rounded-2xl shadow-green-900/10",
        accentShape: "leaf",
    },
    {
        id: "rose-gold-lux",
        name: "Rose Gold Luxury",
        category: "Luxury",
        description: "Elegant rose gold for high-end branding",
        primary: "#fb7185",
        secondary: "#881337",
        accent: "#fda4af",
        dark: "#4c0519",
        light: "#fff1f2",
        gradient: { from: "#fb7185", to: "#fda4af", direction: "to-r" },
        decorationType: "gold-particles",
        headingStyle: "font-light uppercase tracking-widest",
        cardStyle: "rounded-3xl border border-pink-200 shadow-xl",
        accentShape: "diamond",
    },
    {
        id: "cobalt-code",
        name: "Cobalt Code",
        category: "Tech",
        description: "Deep cobalt for serious programming",
        primary: "#2563eb",
        secondary: "#1e3a8a",
        accent: "#60a5fa",
        dark: "#172554",
        light: "#eff6ff",
        gradient: { from: "#2563eb", to: "#60a5fa", direction: "to-r" },
        decorationType: "grid",
        headingStyle: "font-bold uppercase tracking-tight",
        cardStyle: "rounded-xl border border-blue-200 shadow-lg",
        accentShape: "square",
    },
];
